name: docker-nvidia-omniverse

on:
  push:
    branches:
      - main
    paths:
      - "docker/nvidia/omniverse-nvidia.Dockerfile" # only run on changes to this file
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI
  workflow_call: # Allows triggering from another workflow

jobs:
  release:
    uses: ./.github/workflows/_nvidia_docker.yaml
    with:
      dockerfile: docker/nvidia/omniverse-nvidia.Dockerfile
      image: omniverse-nvidia
    secrets: inherit